language: "ruby"
before_install:
  - sudo apt-get -y install python3 python3-pip
install:
  - sudo gem install neocities
  - sudo pip3 install -r requirements
  - mkdir -p $HOME/.config/neocities
  - cat $APIKEY > $HOME/.config/neocities/config
script:
  - make
  - neocities push build
