language: "ruby"
rvm:
  - 2.5.1
before_install:
  - echo $(pwd)
install:
  - sudo gem install neocities
  - sudo pip3 install -r requirements.txt
  - mkdir -p $HOME/.config/neocities
  - if [ "$TRAVIS_BRANCH" == "master" ]; then; echo $APIKEY > $HOME/.config/neocities/config; fi
script:
  - make
  - if [ "$TRAVIS_BRANCH" == "master" ]; then; neocities push build; fi
addons:
  apt:
    packages:
      - python3
      - python3-pip
